### ISSUE TITLE
misleading deployment state

### ISSUE THREAD

**Issue by loomis** [nuvla/api-server#156]
When there are Docker-level errors with a deployment, the deployment state is "STARTED" without any indication of an error. The "STARTED" state should only be set when Docker actually starts the container, rather than when it is created.  Ideally, when the start of the container fails, the error message from the container should be captured and included in the deployment.

**Comment by loomis** [comment]
This will take coordinated changes on the server and on the monitoring job.

**Comment by konstan** [comment]
The monitoring of the service state was implemented in `deployment state` job. It can be extended to do the following. If the number of running replicas is less than the number of desired replicas
- report last error message from the last task that fails to start.
