### ISSUE TITLE
Add type to cimi common metadata

### ISSUE THREAD

**Issue by loomis** [nuvla/api-server#161]
Group rights on a project don't make the project visible to members of the group. This also appears to be the case for applications. This is perhaps caused by the `module` resource not normalizing the ACLs on edits.

**Comment by 0xbase12** [comment]
This is because the users had only view-meta and type is not in metadata.

**Comment by 0xbase12** [comment]
In resources we already have resource-type field. Type will bring confusion.

With @loomis we decided the following:

Rename type to subtype for all resources except for Event and Notification resources which will be renamed to category.
