### ISSUE TITLE
improve commission implementation

### ISSUE THREAD

**Issue by loomis** [nuvla/api-server#177]
Improve the recommission implementation for the nuvlabox resource so that it only creates resources for which it has (correct) information, provide errors (400) with incorrect information, and updates existing resources.

┆Issue is synchronized with this [Trello card](https://trello.com/c/emTt3YVm) by [Unito](https://www.unito.io)

**Comment by loomis** [comment]
The RPi NuvlaBox actually calls the "commission" action at least twice. This is because the compute-api container takes some time to come up, so the first call to "commission" is done before the swarm credentials are available. To avoid this, the swarm credentials must search for an existing swarm service before trying to create one.

**Comment by loomis** [comment]
The current state of the "commission" action implementation avoids creating duplicate resources and allows the resources to be added in separate calls. However, it does not _update_ existing resources. That isn't needed for a first demonstration, so this ticket will be suspended until the updates become necessary.

**Comment by cjdcordeiro** [comment]
the `commission` needs to allow update of the corresponding resources

https://github.com/nuvla/api-server/blob/master/code/src/sixsq/nuvla/server/resources/nuvlabox/utils.clj#L331
