### ISSUE TITLE
Changing the environment variable NUVLA_SUPER_PASSWORD ends up in unusable super user

### ISSUE THREAD

**Issue by schaubl** [nuvla/api-server#198]
On a clean system (no old volumes) if the environment variable `NUVLA_SUPER_PASSWORD` is changed (either with the `docker stack deploy` command or directly in the `docker-compose` file), it will not be possible to login as `super` with the password set in the env variable, neither with the default password.

The mechanism which uses that environment variable to set `super` password at the first boot seems to be broken.

**Comment by loomis** [comment]
I'm unable to reproduce this. The test deployment works both when using the default password and when replacing the default password in the `docker-compose.yml` file. In any case, I've updated the `docker-compose.yml` file to make it easier to change the password value consistently from the shell. I've also updated the README.
