### ISSUE TITLE
NuvlaBox status heartbeat

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/api-server#210]
next-heartbeat field is now sent from NuvlaBox agent. 
The issue with that is : if the clock of the NuvlaBox is not synchronized, the heartbeat will be most probably false and we can't determine if the box is online or offline.

We should use server clock instead to minimize the variance of clock's.

What if next heartbeat is replaced by 'updated' field. 

NuvlaBox use the refresh-interval value to now when it should refresh the status.

UI can use updated field + refresh interval to know when the next check should occur to determine online or offline. But this logic will be replicated in api.
What if when we get, or search for NuvlaBoxes status, a calculated field is added which say if the box is online or offline.

**Comment by loomis** [comment]
I think an easier solution would be simply to update the value of next-heartbeat to (now + refresh interval) when the nuvlabox-status resource is updated. This keeps the current logic on the UI and doesn't require the server to update resources on the fly for every get and query.

**Comment by cjdcordeiro** [comment]
the problem is that the NB `now` is not trustworthy

**Comment by loomis** [comment]
I understand the problem. However, modifying the resource once, by the server, when it is updated will be much more efficient than having to update the resource on the fly every time it is pulled from the database. Both solutions work, even when the time on the NuvlaBox is not correctly synchronized.
