### ISSUE TITLE
Cannot fully share a NuvlaBox

### ISSUE THREAD

**Issue by schaubl** [nuvla/api-server#227]
When a NuvlaBox is activated, a `nuvlabox-status` document is created. 
The ACL of this document doesn't allow the `owner` of the `nuvlabox` to edit ACL.
So the owner of the NuvlaBox cannot allow another user to "view" the `nuvlabox-status` without asking the super user.

**Comment by 0xbase12** [comment]
## Share NuvlaBox
Alternatives:
- Use group to share a NB
- Individual documents updates on change of ACL of nuvlabox document

### Use group to share a NB
- At NuvlaBox creation time, create a group/uuid linked to the NB
- Sub-resources are created with the group-uuid  in **view-acl**
- Add the group/uuid to the NB document
- At decommission time of the NB, delete the group

To share the NB, add the user to the NB group/uuid.

### Individual documents updates on change of ACL of nuvlabox document
When ACL of nuvlabox document is changed, update following documents accordingly:
 - nuvlabox-status/uuid
 - infrastructure-service-group/uuid
 - infrastructure-service/uuid swarm
 - infrastructure-service/uuid minio
 - credential/uuid swarm
 - etc.
 - nuvlabox/uuid
