### ISSUE TITLE
API documentation should be visible to ANON

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#229]
https://nuvla.io/ui/documentation

**Comment by 0xbase12** [comment]
@cjdcordeiro it's already the case if you go directly to the link you can see it.

**Comment by loomis** [comment]
@cjdcordeiro For the resource metadata collection, the default ACL allows "query" by group/nuvla-anon. Similarly, the default ACL for individual resources allows "view-data" for group/nuvla-anon. The commands (without authentication): 

```sh
curl https://nuvla.io/api/resource-metadata
curl https://nuvla.io/api/resource-metadata/user-template-email-invitation
```

both return the expected information.

There doesn't seem to be anything wrong on the server side.  As @0xbase12 pointed out, on the UI the URL https://nuvla.io/ui/documentation also provides the metadata without authentication.

Is this issue intended as a request for a tab or button that's available on the UI when a user has not logged in?
