### ISSUE TITLE
by default, any Nuvla user can see all users

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#230]
just go to https://nuvla.io/api/user and you'll get the full list of users

**Comment by loomis** [comment]
The default ACL for the user collection allows anonymous "query" and "add" to permit the user registration feature to work. 

The default ACL for individual user resources allows any authenticated user ("group/nuvla-user") to view the metadata ("view-meta") of the resource. This is primarily to allow the principals within an ACL to be resolved to a human-readable value. Any user can change the ACL of their user resource to limit the visibility of the metadata.

As the name often contains email addresses, the default may leak some information about users. If this is a concern, the default ACL can be changed to not allow the metadata to be viewed (with ACLs becoming more opaque) or the default names can be changed to something less sensitive.

**Comment by loomis** [comment]
The possible options for changing the behavior are:

 - `no change`: Authenticated users can list other users and see the name/description in the user resources. For users that registered with a method tied to an email address, the name attribute contains the email address. A user at any time can change the ACL of their user resource to hide the metadata from other authenticated users. The users cannot change the value of the name attribute currently. 

 - `change default name value`: Keep the currently implementation but provide another human-friendly value for the name attribute. This could be provided at registration, be randomly generated from a dictionary, etc. 

 - `allow name value to be changed`: Treat the name/description as editable fields (like for most resources). This allows the user to provide any display name (or none) that they want to show to other authenticated users. As the name is not unique, there is a potential risk of people impersonating others even though the underlying user id attribute will always be unique. 

 - `remove view-meta`: Remove the view-meta right from all user resources. This means that authenticated users will not be able to see other users' metadata. This impacts mainly the UI, where it will not be able to display friendly names for ACLs, groups, etc. 

 - `hybrid`: Any combination of the above changes.

**Comment by cjdcordeiro** [comment]
my vote goes for `remove view-meta`

**Comment by loomis** [comment]
> The `view-meta` could be given by default for each "group" the user is part of. So that by default users that are on the same group can easily add&see users with their name on the ACLs.

I don't see this as being a workable solution. It creates a direct linkage between updates to a group and modifications of a user resource. Moreover, the user metadata then becomes visible to members of the group, regardless of the wishes of the user him/herself.  For mapping of friendly names to user id's, a solution based on user-identifier resources would not involve linked updates of resources and arguably would provide better guarantees on uniqueness and minimization of exposed information.

**Comment by loomis** [comment]
The implemented change allows a query of the user resource collection only by an administrator; normal users cannot query the user resource collection. In addition, the default ACL for the user resource has been changed so that the user has all rights to the resource except `edit-acl`. As before the owner of the resource is `group/nuvla-admin`.

This change effectively means that all queries of user resources are forbidden to normal users. With this change, the UI or any other normal client cannot resolve a user id to a human-friendly name. If desired, this resolution should be managed through the user-identifier resource, after considering the security implications.
