### ISSUE TITLE
Port internal authentication method reset feature

### ISSUE THREAD

**Issue by mebster** [nuvla/api-server#27]
Linked to nuvla/ui/issues/5

**Comment by 0xbase12** [comment]
The solution will require a new session template named reset-password.

The session template require following attributes: username new-password

Session reset password will do the following:
- Create a session for the user
- Create cookie claims for the user
- Create callback with action reset-password on targetResource user-id with data with cookies claims and new hashed password
- Send email with callback link to the user:

When the user execute the callback:
- The hashed password replace the old password
- The set cookies is sent to the user

The user is loged in and have a new password
