### ISSUE TITLE
add `enable-stream` and `disable-stream` actions to nb usb peripheral resource

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#278]

**Comment by 0xbase12** [comment]
@cjdcordeiro just to be clear about implementation, when the device have a class "Video" or "Audio" the enable-stream and disable-stream are available for users which have a manage right.

The job actions have not been implemented yet, so to be done by you I suppose.

The enable-stream put a job 'enable-stream' with target-resource pointed on the NB peripheral id and the disable-stream also but the action is 'disable-stream'. 

Both actions are always available for users all the time even if the streaming is already enabled.

**Comment by cjdcordeiro** [comment]
> @cjdcordeiro just to be clear about implementation, when the device have a class "Video" or "Audio" the enable-stream and disable-stream are available for users which have a manage right.

just "video" for this action

> The job actions have not been implemented yet, so to be done by you I suppose.

yes, I'll create the jobs. They'll be similar to the already existing `nuvlabox-reboot` for example

> The enable-stream put a job 'enable-stream' with target-resource pointed on the NB peripheral id and the disable-stream also but the action is 'disable-stream'.

the target-resource should be the parent of the peripheral resource (the nuvlabox resource). This way we avoid doing an extra query on the job-engine side

> Both actions are always available for users all the time even if the streaming is already enabled.

so the logic is:
```
if data-gateway-enabled exists && "video" in classes:
    if data-gateway-enabled:
        set action disable-stream
    else:
        set action enable-stream
```
