### ISSUE TITLE
add new `kind` attribute to infrastructure-service and credential resources

### ISSUE THREAD

**Issue by konstan** [nuvla/api-server#314]
Because it's possible to have more than one resource of the same `subtype` in infrastructure-service-group there is a need to distinguish among them. On example of GNSS: two `subtype: S3` resources are present in infrastructure-service-group, they have different purpose and need to be distinguished by clients via API.

**Comment by 0xbase12** [comment]
Could you consider to use common attribute tag to make that distinction?

**Comment by konstan** [comment]
Do you mean `tag`? I didn't know about that attribute. Where is it defined?

```
✔ ~/code/nuvla/api-server/code/src/sixsq/nuvla/server/resources/spec [master|…1]
14:32 $ grep -r tag ./*
./common.cljc:(s/def ::tags
./common.cljc:      (assoc :name "tags"
./common.cljc:             :json-schema/description "client defined tags of the resource"
./common.cljc:            ::tags
./common.cljc:            ::tags
./common.cljc:            ::tags
./container.cljc:(s/def ::tag
./container.cljc:      (assoc :name "tag"
./container.cljc:             :json-schema/description "tag"
./container.cljc:                                            ::tag
./user_identifier.cljc:            ::common/tags
✔ ~/code/nuvla/api-server/code/src/sixsq/nuvla/server/resources/spec [master|…1]
14:32 $
```

**Comment by 0xbase12** [comment]
Sorry I meant `tags` a list of string

**Comment by konstan** [comment]
Cool. Yes, sure I can you this one. I'm closing this ticket. Thank you.
