### ISSUE TITLE
Deployment data-record map spec change

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/api-server#321]
Actually the data records in deployment are store in following format:

```
{:data-record/1 ["data-set/a"], :data-record/2 ["data-set/a", "data-set/b"], ...}
```
This list is built from data-set filter + timestamp filter (start, end) + full-text search filter
Multiple data-set can be selected.

My suggestion will be to change that to the following:
1) list of data-set ids + filter attribute timestamp start + filter attribute timestamp end + full text filter if needed
 or
2) (filter extracted from data-set/a OR filter extracted from data-set/b) and timestamp >= date-start and timestamp < date-end and full-text-search(optional)

**Comment by konstan** [comment]
I vote for 2.
