### ISSUE TITLE
Email address not saved when a user register with GitHub

### ISSUE THREAD

**Issue by schaubl** [nuvla/api-server#323]

**Comment by 0xbase12** [comment]
After verification, the code actually do retrieve email and save it when available.
https://github.com/nuvla/api-server/blob/master/code/src/sixsq/nuvla/server/resources/callback_create_user_github.clj#L18
Perhaps a bug or change in github api:
https://github.com/nuvla/api-server/blob/master/code/src/sixsq/nuvla/server/resources/callback_create_user_github.clj#L28
Need more tries and investigation

**Comment by 0xbase12** [comment]
No changes in Github api.
The retrieved email from github is only registred only as user-identifier and not as an email with `user-minimum` template creation. `user-minimum` template is used for external auth, so the email issue is in all external auth
