### ISSUE TITLE
design and add SSH workflow to NB commissioning

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#335]
Nuvla creates private key, sends to user, and asks NB to authorize respective public key

**Comment by cjdcordeiro** [comment]
# 1. Lifetime SSH keypair, generated at commissioning time

 1. user creates a new nuvlabox resource and install the NuvlaBox engine on a device
 2. the NuvlaBox Engine with automatically activate and commission itself 
 3. during commissioning, Nuvla will also generate a new credential type "SSH":
    1. with `parent` set to that nuvlabox/uuid 
    2. with `acl/owner` set to the NB owner
    3. send notification to the user
    4. send public key back to the NuvlaBox Engine, so that it can add it to the _authorized_keys_
 4. on the NuvlaBox edge detail page, a new available action will be `SSH`, which will give the private key back to the user, together with an ssh:// href command 
 5. (optional...or to be implemented later) on the NuvlaBox edge detail page, a new available action will be `Console`, which will use that SSH credential to tunnel into the NB via a Web Console, in Nuvla

**NOTE:** this method can also be applied at NuvlaBox creation, instead of COMMISSIONING

# 2. Time-limited, on-demand, SSH keypair, via NuvlaBox actions

 1. users create and install the NuvlaBox as usual
 2. a new action is added to the NuvlaBox: "Create SSH connection"
    1. this will generate a new Nuvla credential of type SSH, with parent "nuvlabox/uuid" and same owner as the NuvlaBox, **BUT**, with an expiry date
    2. the action will ask the NuvlaBox Engine Management API to add this new public SSH key to the _authorized_keys_
    3. once the credential expires, the key is removed from the NuvlaBox and Nuvla
    4. apart from the Nuvla notification and ssh:// link, the user will also be prompted about starting a Web Console with that new SSH keypair

**Comment by konstan** [comment]
@cjdcordeiro 
Start with 1., plus let users to provide their own public keys to be pushed to the NB. User-provided public keys are kept on Nuvla as well and can be reused for future NBs.

**Comment by cjdcordeiro** [comment]
# 3. Combination of 1 and 2

 1. at NuvlaBox creation time, the user will be asked if:
    1. create a new SSH key for the NuvlaBox
        1. in this case, together with the installation instructions, the user is also give the private SSH key 
    2. re-use an existing one from Nuvla
 2. the NuvlaBox Engine (management-api) will accept an new env var called NUVLABOX_SSH_PUB_KEY which is optional and contains the initial SSH pub key to be added to the host
 3. the NuvlaBox resource will have a new attribute, which is a list of the SSH keys associated with it
 3. the following new actions will be added to the NuvlaBox:
    1. **add new SSH key**: user can select an existing one from Nuvla, let Nuvla generate a new one, or upload its own public key. Nuvla will send the public key to the NuvlaBox Mgmt API and give the user the ssh:// instructions
    2. **revoke SSH key**: user can select a specific key to be removed from that NuvlaBox (this doesn't delete the SSH credential from Nuvla). The NuvlaBox will remove it from the host
    3. **web console** and **remote command** (future options): will synchronously generate and destroy an SSH keypair, just for the duration of the action

**NOTE:** for now all SSH keys are indefinite. The manual revoking ensures the security for now, and later on expiration dates can be added - a new mechanism for detecting expired keys and removing them from the NuvlaBox is needed...TBD

**PROBLEM**: if the credential is deleted from Nuvla, it doesn't mean it will stop working on the NuvlaBoxes. A DELETE hook will be needed for this type of credentials...

**Comment by cjdcordeiro** [comment]
created implementation plan at https://github.com/nuvla/api-server/issues/362
