### ISSUE TITLE
expand peripheral telemetry to accomodate telemetry data

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#348]
new attribute:

```
"resources": [{
    "unit": "cuda cores",
    "capacity": 100,
    "load": 50
}, ...]
```

**Comment by QuietSwami** [comment]
Peripheral Manager GPU
`
"resources":[{
    "unit": "cuda cores",
   "capacity": 100
}]
`

**Comment by cjdcordeiro** [comment]
what are the other attributes you have available?

**Comment by QuietSwami** [comment]
Regarding the cuda cores is that. I have other information regarding the device, but I think it should go to other attribute fields (device name, memory capacity [not directly connected to cuda cores])

**Comment by cjdcordeiro** [comment]
np. please paste the full structure u have atm anyway

**Comment by QuietSwami** [comment]
Peripheral Manager GPU:

```

        'available': True,
        'name': 'Graphics Processing Unit',
        'vendor': 'Nvidia',
        'classes': ['gpu'],
        'identifier': identifier,
        'additional-assets': {
              'device-information': {
                     'cuda-cores': 100,
                     'multiprocessors': 4,
                     'memory': 2048
                     'gpu-clock': 1024,
                     'memory-clock': 1024
             }
             'devices': ['/dev/nvidia0', ....],
             'libraries': ['/usr/lib/....']
       }
```

This is all the information that is available.

**Comment by QuietSwami** [comment]
Peripheral Manager Ethernet

```

{
        'available': True,
        'name': 'Network',
        'classes': ['network'],
        'identifier': identifier,
        'additional-assets': {
              'ethernet-devices':  {
                      ip: {
                           'status': up/down,
                           'hostname': 'name'
                      },
                      ...
              }, 
              'wifi-devices':  {
                     'wifi name': {
                             'strength': 1/2/3/4/5
                             'security type: 'wpa'
                     },
                    ...
             }
       }
}

```

**Comment by QuietSwami** [comment]
Peripheral Manager Bluetooth

```
            'available': True,
            'name': 'Bluetooth',
            'classes': ['bluetooth'],
            'identifier': bluetooth,
            'additional-assets': {
                    'devices':  [(mac_addr_1, hostname_1), (mac_addr_2, hostname_2), ...]
            }
```

**Comment by cjdcordeiro** [comment]
> Peripheral Manager Ethernet
> 
> ```
> 
> {
>         'available': True,
>         'name': 'Network',
>         'classes': ['network'],
>         'identifier': identifier,
>         'additional-assets': {
>               'ethernet-devices':  {
>                       ip: {
>                            'status': up/down,
>                            'hostname': 'name'
>                       },
>                       ...
>               }, 
>               'wifi-devices':  {
>                      'wifi name': {
>                              'strength': 1/2/3/4/5
>                              'security type: 'wpa'
>                      },
>                     ...
>              }
>        }
> }
> ```

this should become:

```json
{
        'available': True if status == 'up' else False,
        'name': 'hostname/deviceName',
        'classes': ['audio', 'video', 'misc', 'network', '...(try to infer)'],
        'identifier': identifier,
        'interface': 'ethernet',
        ...
       }
}
```

**Comment by cjdcordeiro** [comment]
> Peripheral Manager Bluetooth
> 
> ```
>             'available': True,
>             'name': 'Bluetooth',
>             'classes': ['bluetooth'],
>             'identifier': bluetooth,
>             'additional-assets': {
>                     'devices':  [(mac_addr_1, hostname_1), (mac_addr_2, hostname_2), ...]
>             }
> ```

this should become

```json
{
            "available": True/False,
            "name": hostname,
            "classes": ["computer", "audio", "video", "tv", ...],
            "identifier": mac_addr,
            "interface": "bluetooth",
            "vendor": ...
}
```

**Comment by QuietSwami** [comment]
> > Peripheral Manager Bluetooth
> > ```
> >             'available': True,
> >             'name': 'Bluetooth',
> >             'classes': ['bluetooth'],
> >             'identifier': bluetooth,
> >             'additional-assets': {
> >                     'devices':  [(mac_addr_1, hostname_1), (mac_addr_2, hostname_2), ...]
> >             }
> > ```
> 
> this should become
> 
> ```json
> {
>             "available": True/False,
>             "name": hostname,
>             "classes": ["computer", "audio", "video", "tv", ...],
>             "identifier": mac_addr,
>             "interface": "bluetooth",
>             "vendor": ...
> }
> ```

For each device available? Or do I include a list of devices?

**Comment by cjdcordeiro** [comment]
each peripheral = 1 Nuvla peripheral resource

**Comment by cjdcordeiro** [comment]
@QuietSwami the api-server has been updated. the `nuvlabox-peripheral` resource now also accepts the extended resources attribute as defined in this ticket's description
