### ISSUE TITLE
issue when bulk deleting peripheral resources

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#371]
<img width="1007" alt="Screen Shot 2020-07-01 at 9 15 50 AM" src="https://user-images.githubusercontent.com/4047767/86214537-9695e980-bb7b-11ea-9fac-2436094d5f6b.png">

**Comment by 0xbase12** [comment]
This is because peripheral resource does not support bulk delete. You implement it if needed.
You are using super account, I think. So by default super will be able to call any operation or action even if it's not implemented.
