### ISSUE TITLE
Switch group

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/api-server#373]
**Currently**, at creation of session, user groups are extracted and added to claims in the cookie.
This has the impact to show all resources of all claims mixed-up.

**In futur** we want at session creation to only get the user-id and generic groups in claims: nuvla-anon, nuvla-user and user-id.
When a switch group is used, the group-id will come and replace user-id in claims. This will have the impact to make the server filter the resources which are visible to the group.

This change will have an impact on creation of api-key. So when a user ask for creation of an api-key, he well get the reduced claims. (This can have an impact on what you do @konstan). To be checked, creation of api-key all over api-server. (e.g. deployment api-key generation to check if the behavior will not be impacted by the switch group change).

-------

To allow a proper switch role instead of a act as only, we have to do the following:
- Extracted groups are added to a new group-list attribute in the cookie.
- By default, at authentication the claims are only the user-id and nuvla-user and nuvla-anon
- When user want to switch to group, the user-id is dropped from claims and the group is added to the claims.
- active-claim attribute point to the switched group and user-id attribute point to the original user 

We want also to have 2 new cimi attributes for all resources to allow tracing of who did what:
- created-by
- updated-by

**Comment by 0xbase12** [comment]
What do you prefer switch group or switch role ?
Vote here: 
🅰️ for switch group
🅱️ for switch role

**Comment by schaubl** [comment]
🅾️ Switch organization

**Comment by konstan** [comment]
For the info on the case of GNSS. At the moment, the deployment needs (apart from access to deployment parameters) to obtain credentials of S3 (on cloud or edge). This requires following view rights (GET and PUT on collection (as search)) on
- GET deployment parent: credentials/“IS credential”
- GET IS credential parent: infrastructure-service/“IS”, extract parent which is “IS group”
- PUT find all IS with the parent “IS parent” in infrastructure-service/, and select “IS S3”
- PUT find credential who’s parent is “IS S3".
Restricting api-key to only deployment is not going to work for the above (obvious).

Possible solution:

Along with the generation of api-key for deployment/, allow user to create api-key templates defining access to resources with preferred ACLs that users needs. Then, let attach the templates to apps or let select the template right before deployment. They generated api-key, will contain default access to the deployment/UUID and for the resources with ACLs user pre-defined.

So, for the GNSS case above, me (as app developer) would create api-key template with view (RO) access to credentials/ and infrastructure-service/. Then, I would attach this template to my application. When the application gets started by a user, Nuvla generates api-key for the deployment following the api-key template that was attached to the application (resources + ACLs). This api-key of course for the active user group or user id.

**Comment by schaubl** [comment]
> Restricting api-key to only deployment is not going to work for the above (obvious).

But it should work with the checkbox we discussed yesterday. (Give all permissions of the current context)

**Comment by konstan** [comment]
Agreed. Though, the current user context is almost always wider than desirable for long-running applications running in the field.

**Comment by schaubl** [comment]
"Current user context" is the group context if you have "switched to a group".
But it should be fine because If you can deploy as the group, it means that the group has access to these resources. (If not their ACLs can be updated)

**Comment by 0xbase12** [comment]
My question was more about the current user context which will impact the deployment api-key by a reduced claims.
Last comment of @schaubl is in the right direction

**Comment by konstan** [comment]
@schaubl You are lowering your security bar, which is always set quite high and violating PoLP principle :)
If the idea here is to do something quick, then we can opt for the binary approach with "deployment only" or ALL.

There will always be applications that at runtime will require access to Nuvla. And there will always be mistakes in giving ACLs in the groups to where it is not desirable.

So, with the future implementations, I hope we implement the approach I suggested above (or similar), which is as you can see a slight extension of IAM, where you allow to attach per application "security" templates and generate api-keys only when needed (at deployment provisioning time).
