### ISSUE TITLE
[BUG] bulk delete doesn't work when only one resource is selected

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#381]
<img width="1358" alt="Screen Shot 2020-08-07 at 2 03 25 PM" src="https://user-images.githubusercontent.com/4047767/89644052-63035900-d8b7-11ea-90cd-ae74068558fe.png">

**Comment by 0xbase12** [comment]
Not all resources support bulk delete. The UI should hide bulk delete action when the action is not implemented (https://github.com/nuvla/ui/issues/606).
