### ISSUE TITLE
error on all NuvlaBox actions

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#405]
`#error {:message "unknown operation", :data {:status 400, :message "unknown operation", :resource-id "nuvlabox/ed8bf4b1-60ad-433e-bb78-26bb1cc63792"}}`

**Comment by 0xbase12** [comment]
UI side issue, digging, rollback ui in prod to 2.9.0 in meantime

**Comment by 0xbase12** [comment]
Fixed https://github.com/nuvla/ui/commit/7d6e3baf2b7515973b7b93a475c82592c12fd9e7
