### ISSUE TITLE
add pull-mode attributes to deployment

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#413]
in order to support pull-mode job execution, add the following attributes to the deployment spec:
 - modify `state` to also accept the keyword "WAITING"
 - management-engine: (or some other name) to indicate whether the deployment is being managed/monitoring by Nuvla or by an external IS -> {"nuvla-managed", "external"}

**Comment by 0xbase12** [comment]
Do we need the state WAITING ? Can't be also replaced with Starting and to show the execution-mode somewhere ?
Do we need management-engine ? If the deployment is in pull mode, job-distributor will only consider deployment with exectution-mode push

**Comment by cjdcordeiro** [comment]
hum...I think that's open to interpretation...STARTING isn't really representative of its state...PENDING would be ideal...

wrt management-engine, this is the same as execution-mode yes, just renamed...`execution-mode` didn't seem very applicable to a deployment

**Comment by 0xbase12** [comment]
Yes PENDING is a good idea

**Comment by 0xbase12** [comment]
TODO since we add a new state for deployment, check UI code if we define some state checks and take new pending value into account
