### ISSUE TITLE
compile a "pull-mode response" for all NuvlaBox status updates (telemetry)

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#414]
every time NB telemetry is sent to Nuvla, send back an HTTP response with the list of corresponding "WAITING" jobs in Nuvla.

Make sure this response is expanded to include all necessary information for the NB to execute the job (i.e. jobs' target and affected resources, included any necessary credentials to perform the job)

**IMPORTANT**: this response needs to be schemed in a way that is sustainable and recognized by the Job Engine Lite. A proper schema should be agreed upon and given that this response is not a typical Nuvla resource, it needs proper thinking before implementation

**Comment by 0xbase12** [comment]
**NB jobs list that support pull/push:**
 - NB reboot
 - NB add-ssh-key
 - NB revoke-ssh-key
 - NB update-nuvlabox
 - Deployment start
 - Deployment stop
 - Deployment update
 - Deployment logs?

We have jobs with target-resource attribute pointing to deployment/nuvlabox

*List jobs bad solution*
Get all WAITING jobs
Get all deployment of these jobs -> resolve infra service
Get NB pointed by telemetry -> get infra service group -> search for the swarm
…

To build an efficient search jobs request:
we need to get the NB infra id easily. 


A. So a good start is to move infra swarm id to the body of the NB resource.
 -> Add infrastructure-service-swarm with id of swarm at creation time
 -> Migrate script to add this info to NB resource body
 -> (This will help to build list of deployment for a NB)

Infra telemetry-> get NB-> extract swarm-id:
Search job resource with targetResource swarm-id and nb-id

**Comment by cjdcordeiro** [comment]
I don't think the deployment logs are needed, this is a a sync action. 

> A. So a good start is to move infra swarm id to the body of the NB resource.
Note that it can be also a k8s IS. So better to do this as a hook at commissioning time.
