### ISSUE TITLE
Add NuvlaBox level events from telemetry

### ISSUE THREAD

**Issue by mebster** [nuvla/api-server#419]
When telemetry values go out of a certain threshold, trigger an alert event to subscribed users:

1. CPU too high (e.g. >90%)
1. Disk space too low (e.g. <10%)
1. Free RAM too low (e.g. ??)
1. Connectivity lost (from Nuvla) (e.g. if lost for more than 5 minutes?)
1. Sudden and sustained spike in network usage (?? nice to have)

Could we set reasonable threshold to start with, or do we need to introduce user parameterised alerts right away?

┆Issue is synchronized with this [Trello card](https://trello.com/c/iJvbqrSV) by [Unito](https://www.unito.io)

**Comment by konstan** [comment]
- [x] CPU too high (e.g. >90%)
- [x] Disk space too low (e.g. <10%) - I was done as disk space usage in %. Hence, notify on when "disk usage is above X%".
- [x] Free RAM too low (e.g. ??) - Same as for disk space.
- [ ] Connectivity lost (from Nuvla) (e.g. if lost for more than 5 minutes?)
- [ ] Sudden and sustained spike in network usage (?? nice to have)



> Could we set reasonable threshold to start with, or do we need to introduce user parameterised alerts right away?

Currently, UI is not providing defaults and lets users to set the value. 

We can pre-set defaults and let user accept or change them.

**Comment by konstan** [comment]
`Sudden and sustained spike in network usage (?? nice to have)` will be handled by new epic that will be created in SixSq org.
