### ISSUE TITLE
Publish to kafka acting as sync call instead of async

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/api-server#459]
When Kafka server is not responding, the call to `sixsq.nuvla.server.util.kafka-crud/publish-on-add` is waiting a timeout of 60s before returning. 
The initial request to api-server is stuck in the meantime.

┆Issue is synchronized with this [Trello card](https://trello.com/c/e5UdPvaH) by [Unito](https://www.unito.io)

**Comment by konstan** [comment]
It's no-op only if Kafka wasn't running during the nuvla server startup and hence the Kafka publisher wasn't created. The fix is needed, in case, Kafka becomes unavailable at runtime.

**Comment by 0xbase12** [comment]
I tried to start the server without kafka and removed the env var that define the kafka endpoint for api-server but it was not acting as a no-op

**Comment by konstan** [comment]
Closing. Addressed by https://github.com/nuvla/api-server/pull/640
