### ISSUE TITLE
implement NB partial decommissioning and add "disable" flag to IS credential

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#462]
as part of the NB clustering work, whenever a NuvlaBox becomes a worker, users shouldn't be able to deploy app to it anymore (even though the Docker API still exists).

The easier implementation for this is:
 - allow for a partial commissioning, whereby the NB can tell Nuvla to decommission certain resources, like the swarm join tokens (they don't exist for worker anymore)
 - let the NB (via the commissioning) set the corresponding IS credential as "inactive" (or "disabled" or "cant-deploy"...whatever), so that the worker IS doesn't show in the app deployment modal, but the credential is still there to be used by the job-engine (for the NB mgmt-api)

**Comment by 0xbase12** [comment]
Name of the action:
  - partial-decommission
  - become-worker
  - other proposition ?
  
Action available under condition: 
  - (is-nuvlabox or is-admin) and state='COMMISSIONED'
  
Resource change:
  - Should the state change?
  - Should we have a field that indicate that this NB is a worker
  
Sub-ressource change:
  - Delete exisiting credeentials "swarm join tokens"
  - Change credential infrastructure swarm to inactive

**Comment by 0xbase12** [comment]
https://github.com/nuvla/ui/issues/575

**Comment by cjdcordeiro** [comment]
> Name of the action:

can't it be the same one? and just the the disabling of resources happen based on the attributes being sent?

> (is-nuvlabox or is-admin) and state='COMMISSIONED'

not necessarily commissioned. it can be activated as well. thus the comment above...this is just a commissioning with exclusion of resources

> Should the state change?

no

> Should we have a field that indicate that this NB is a worker

there is one already in the NB status, which is pushed as telemetry

**Comment by cjdcordeiro** [comment]
why not commission? 

The reason I'm pushing for commission is to keep it simple in the NB.

The NB doesn't know whether it should commission or decommission...it just knows that has been a change in the underlying infrastructure, therefore "these are the affected attributes"

why not use `commission`, with a new attribute (similar to PUT requests), like `select` or `exclude` that indicate that the IS has changed

Plus, if we use decommission, that means adding yet another upstream request to the NB, cause it is going to commission anyway

**Comment by 0xbase12** [comment]
`select` is used in cimi to delete a field in a resource on edit request, in this case it's not really a field and not an edit.

To make it more clear to me can you give me an example of a commission request to transform a nb into a worker.

**Comment by cjdcordeiro** [comment]
the commission doesn't transform the NB. The commission is independent of the NB state. It just reports infra attributes.

`POST /api/nb/uuid/commission {'tags': ['blabla'], 'swarm-token-worker': 'asdvasd'}`

atm, this request simply edits the swarm-token-worker credential.

However, what we need now is something like:
`POST /api/nb/uuid/commission {'tags': ['blabla2'], 'removed': ['swarm-token-worker']}`

**Comment by 0xbase12** [comment]
Okey and how would you request to disable swarm/kubernetes credential?

**Comment by cjdcordeiro** [comment]
The problem here is that we have 2 behaviors:
1 - a certain attr is gone, and therefore must be deletes (example: swarm-join-token credentials)
2 - the node became part of a cluster, therefore its compute-api should not be used -> disable IS and IS creds

**Comment by 0xbase12** [comment]
After discussion with @cjdcordeiro:

A new field is passed during commission action that allow to request from server to remove some resources linked to the NB. 

`removed`: List of string with #{swarm-token-manager, swarm-token-worker, swarm-client-key, swarm-endpoint}

In case of indication of a resource in `removed` field, the related information to this resource are ignored.
e.g. removed=['swarm-token-manager'] and swarm-token-manager field = 'anything', the latest is ignored and the resource is deleted

**Comment by cjdcordeiro** [comment]
@0xbase12 this isn't deleting the ISG. Is that on purpose? It doens't need to..just fyi

**Comment by 0xbase12** [comment]
I didn't instructed to delete it. If it's needed we can do that also.
