### ISSUE TITLE
[bug] nuvlabox gets commissioned after decommissioning

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#484]
Steps to reproduce:
 - get a nb
 - commission
 - decommission
 - wait

it will change its state automatically back to commissioned

**Comment by 0xbase12** [comment]
The only change regarding nuvlabox in last version of api-server is clustering.

I'm unable to reproduce this bug on api-server in following condition:
- Create nuvlabox
- Activate  nuvlabox from api page
- Commission nuvlabox from api page
- Decommission nuvlabox from api page
- Wait job to finish and be decommissioned
- The nuvlabox will remain in decommissioned state

The one responsible for calling commission on every change on nuvlabox is the agent.  The question is there something changed on agent that could call commission on decommissioned nuvlabox?

**Comment by cjdcordeiro** [comment]
I cannot reproduce it anymore either...let's call it a glitch and close for now

**Comment by cjdcordeiro** [comment]
ok so found it again. And it's not new. It just doesn't happen always. It is the agent which might send a recommission before noticing the nb has been decommissioned. 

I'll try to be preemptive on the NBE side, but this won't be applied to older NBE versions. @0xbase12 is this feature made on purpose? What's the use case for commissionig a decommissioned nb instead of recreating?
