### ISSUE TITLE
Add "string" type to subscription

### ISSUE THREAD

**Issue by mebster** [nuvla/api-server#493]
Currently, the following are allowed: "boolean", "numeric", "set".

Add "string", in order to allow the user to define a condition matching any string.  This will be used to match 'content-type' on the 'data-record' resource.  In the ui, metadata on the selected resource is used to pull the known content-types. 

-- Relevant specs -------

:sixsq.nuvla.server.resources.spec.subscription-config/condition:

**Comment by konstan** [comment]
@mebster I believe you meant `subscription-config/kind` not `subscription-config/condition`.

Then as the contract between the UI and stream processor, in the case of the "string" kind - here is what I suggest `:condition` can be
```
:condition  "is | is not | starts with | contains | ends with"
```
Works?
The translation of the `:condition` will be done to KSQL string matching functions.

**Comment by mebster** [comment]
My bad. Yes you're right
