### ISSUE TITLE
Group invitation by email

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/api-server#499]
Allow a group manager to invite a user to join the group by entering his email/user-identifier.

1) User call invite new invite action on group and pass user-identifier in the body of the request.
2) Server check if user-identifier exist. If doesn't exist or exist send ok
3) If exist, try get email address of the invited user.
4) Create callback to add user-id to users list of the group.
5) Send email with callback url accept within invitation email template

Questions: 
1) Group manager should be able to add user directly by editing users field or we restrict this to only admin user
2) Group manager should have edit right or only manage on the group to allow him to invite?
3) Should user be able to create group?
4) Can group manager be able to cancel invitation? Needed?

**Comment by cjdcordeiro** [comment]
> Group manager should have edit right or only manage on the group to allow him to invite?

I'd say edit. It can become handy to change other attributes of the group as well

> Should user be able to create group

yes, in the same lines as the answer above

> Can group manager be able to cancel invitation? Needed?

canceling an ongoing invitation could be nice. But maybe adding a 'revoke' or 'remove' user from group would be better and fulfil both ongoing and fulfilled invitations

**Comment by 0xbase12** [comment]
Questions answers:
1. Yes he should be able to edit directly, invite is a helper in case he doesn't know the user-id.
2. Yes should have edit-data
3. Yes
4. Nice to have. To be considered on later.

When user doesn't exist, create it instead. Email with terms sent with callback that should on execution activate user, validate email and add user to group invited to.

Later on we will consider to only allow user to be added to a group via email invitation. If user exist say only accept to join group.

To improve discovery of users that are in common groups, a mapping map of user-id to validated email will be available through resource session.
