### ISSUE TITLE
add support for geo or shape queries 

### ISSUE THREAD

**Issue by konstan** [nuvla/api-server#529]
This is to support geo queries (as polygons) on the data-records. Evaluate which one is more suitable for the use case in question (see label on the issue).

References:
https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-queries.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/shape-queries.html

Dependant issue on UI https://github.com/nuvla/ui/issues/714

**Comment by 0xbase12** [comment]
I think the https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-shape-query.html are more advanced and allow to support to select documents that have geopoint WITHIN or DISJOINT an enveloppe(bbox) or a polygone.

Cimi filter syntax:

`<attribute-name>`   `<operation IN | OUT>`  `<shape ENVELOPE[[minLon, maxLat], [maxLon, minLat]]> | POLYGONE[[long, lat], [long, lat], ...]>`

E.g. location IN ENVELOPE[ [5.789795, 47.798397], [10.623779, 45.702343] ]
