### ISSUE TITLE
date formating from string fails in tests

### ISSUE THREAD

**Issue by FabianMk** [nuvla/api-server#650]
Running the spec tests: 

`lein test :only sixsq.nuvla.server.resources.spec.vulnerability-test/check-vulnerability-schema`

fails on some machines with: 
```
-- Spec failed --------------------
  {:description ...,
   :updated ...,
   :name ...,
   :created "1964-08-25T10:00:00.00Z",
            ^^^^^^^^^^^^^^^^^^^^^^^^^
   :modified ...,
   :reference ...,
   :id ...,
   :score ...,
   :severity ...,
   :resource-type ...,
   :acl ...}
should satisfy
  date-from-str
```
The 00 in milliseconds of the timestamp string used in tests causes `src/sixsq/nuvla/server/util/time/date-from-str` to throw an exception.

**Comment by 0xbase12** [comment]
Fixed by #651
