### ISSUE TITLE
Word email customers end of trial

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/api-server#660]

**Comment by 0xbase12** [comment]
1. Email before end of trial. 

- Trial end date. Also show in how many days to be more user friendly.
- List resources that will be freezed (no payment method) OR List of billable resources (has payment method)
- Action to accomplish to keep resources running (when no payment method)

2. Email after trial ended
- Trial ended at following date
- List billable resources that was freezed (when user hasn't add a payment method)
- Action to unfreeze (when user hasn't add a payment method)

**Comment by 0xbase12** [comment]
@FabianMk You can find in this namespace how emails are built `sixsq.nuvla.server.resources.email.utils`

**Comment by FabianMk** [comment]
Draft: 

# before end of trial 

Hey,

Your Nuvla.io trial is will end in XXXX days. Now is a good time to upgrade and get all the awesome benefits.

Your account will be deactivated when the trial ends. The following resources will be frozen: 

* resource 1
* resource 2

You’re also going to lose access to any data you have in Nuvla.io. You no longer will be able to receive data from your Nuvla Edge devices on Nuvla.io. 

Do not worry! We keep it safe with us for when you decide to upgrade.

By upgrading now, you will ensure your data flows stays active. Just add a payment method in your Nulva.io account. 

Luckily you still have 5 days to upgrade.

Best
Marc-Elian Bégin


# after trial ended

Hey,

Your Nuvla.io trail expired today. We froze the following resources:

* resource 1
* resource 2

If you want to unfreeze them just add a payment method in your Nuvla.io account and choose a subscription: [URL-to-salespage]

Would you mind sharing briefly with me what kept your from upgrading?
Feel free to hit reply here or we can just schedule a quick 5-minute Skype/Zoom/Hangouts call. 
Would really love to hear your feedback.

Thank you,

Marc-Elian Bégin

**Comment by FabianMk** [comment]
added 1st draft to trial branch to the email utils

**Comment by FabianMk** [comment]
added 2nd draft for trial ended email to trial branch

**Comment by FabianMk** [comment]
as discussed the resources could be displayed as:
<h4>Deployments</h4>
Dep1
Dep2
Dep3
<h4>NuvlaEdge devices</h4>
NB1
NB2

where 

Deployment id='deployment/873ab926-4865-41ca-84bd-d6e1b1913320' name='Nginx simple app'

<a href="https://nuvla.io/ui/deployment/873ab926-4865-41ca-84bd-d6e1b1913320">Deployment: Nginx simple app (873ab926)</a>

**Comment by FabianMk** [comment]
@0xbase12 listing the resources in the email makes the templating more complex. I suggest we finish a basic email first

**Comment by FabianMk** [comment]
@mebster here are the email drafts for the trial end mailing: 
<img width="450" alt="Screenshot 2022-03-14 at 13 42 32" src="https://user-images.githubusercontent.com/8279995/158118717-099742d6-ce52-4cb7-a498-f506516b4a68.png">
<img width="454" alt="Screenshot 2022-03-14 at 13 50 35" src="https://user-images.githubusercontent.com/8279995/158119751-1523fe6b-dd20-4c32-aa7f-b28e6b3dcdc9.png">

**Comment by 0xbase12** [comment]
Here is an example of Stripe email warning about end of trial period that we can enable 

<img width="1134" alt="Screenshot 2022-03-17 at 13 20 29" src="https://user-images.githubusercontent.com/5518233/158827600-dde50a08-0e19-4213-92a8-dd492e0bd13e.png">
