### ISSUE TITLE
Fix bugs in host level management (playbooks)

### ISSUE THREAD

**Issue by schaubl** [nuvla/api-server#720]
I found some bugs in the feature `host level management (playbooks)`:

- [x] When enabling it, the _api-server_ return an URL endpoint with a double `/nuvlabox` (see screenshot at the end) https://github.com/nuvla/api-server/issues/708
- [x] URL is hardcoded to https://nuvla.io
- [x] When enabling it, the crontab time is `* 0 * * *` which means: every minute from 0:00am to 0:59am (see screenshot at the end). It should be `0 */24 * * *` for everyday at midnight or `0 * * * *` for every hour or even configurable.
- [x] Sending playbook output to Nuvla fails if there are double quotes in it.
- [x] The `assemble-playbooks` operation returns a shell script with a missing end curly bracket at the end which prevent it to return its output.

```sh
curl -X POST ${NUVLA_ENDPOINT:-https://nuvla.io}/api/nuvlabox-playbook/<uuid>/save-output -H content-type:application/json -b /tmp/nuvla-cookie  -d "{\"output\": \"$(cat /tmp/nuvlabox-playbook-<uuid>.output)\""
```
`-d "{\"output\": \"$(cat /tmp/nuvlabox-playbook-<uuid>.output)\""` should be 
`-d "{\"output\": \"$(cat /tmp/nuvlabox-playbook-<uuid>.output)\"}"`

---

![Screenshot 2022-11-08 at 18 33 44](https://user-images.githubusercontent.com/2462866/200674187-4a4cd593-5b58-45f0-ad82-ac67baf318a0.png)

**Comment by konstan** [comment]
@schaubl Can you please create an Epic for this (or add to an existing one) in https://github.com/orgs/SixSq/projects/1? Thanks.
