### ISSUE TITLE
NuvlaEdge: do not take into account tags sent during (re)commissioning 

### ISSUE THREAD

**Issue by schaubl** [nuvla/api-server#755]
This is important so that tags edited by user are not replaced by the NuvlaEdge.

Related to: #750

**Comment by MTrost** [comment]
@schaubl Why not merge with current tags?

Merging was also suggested by Nacho in the tasklist issue

**Comment by schaubl** [comment]
Because it's two different things. 
We have "NuvlaEdge tags" (list of strings) and "COE node labels" (list of key&value).

Currently the NuvlaEdge adds (in fact replace) COE node labels into NuvlaEdge tags but if you add a tag on Nuvla it will not be added as a COE node label.

Merging will prevent removing of NuvlaEdge tags when the corresponding COE node label is removed because we will not know if the was a user created tag or a tag imported from COE node labels.

Also NuvlaEdge reports through the telemetry so in the `nuvlabox-status` resource where it has the right to edit.
But these tags are at the level of `nuvlabox` document where NuvlaEdge doesn't have the right to edit so it goes through the "commission" operation to ask Nuvla to add these tags.
So for every change in COE node labels, it will trigger a recommission.
Also informations about the COE are in the `nuvlabox-status` resource.
