### ISSUE TITLE
NuvlaEdge: add a new operation heartbeat

### ISSUE THREAD

**Issue by schaubl** [nuvla/api-server#773]
This new `heartbeat` operation will update a new field `last-heartbeat` with the current time and return the list of `jobs` to execute.

A new field `heartbeat-interval` should be added to `nuvlabox` resource.

~To be discussed if~ This new operation and new field should be on **`nuvlabox`** or ~`nuvlabox-status`~ resource.

Apply this new behavior only on NE with `NUVLA_HEARTBEAT` capability.

Do not forget to update the field `next-heartbeat`.

**Comment by konstan** [comment]
Moved to "In progress". The issue is still being worked on.
