### ISSUE TITLE
Deployment's execution mode is not taken into account when defining job for fetching logs of the deployment components

### ISSUE THREAD

**Issue by konstan** [nuvla/api-server#781]
The execution mode of deployment is not taken into account when defining jobs for fetching logs of the deployment components. Then by default, the execution mode gets set to `push`. This prevents getting logs from NuvlaEdge devices that only support `pull` mode jobs.
https://github.com/nuvla/api-server/blob/master/code/src/sixsq/nuvla/server/resources/resource_log.clj#LL152C24-L152C24

Also, as of now, in the case of deployment in `mixed` execution mode, if it's running on an infrastructure-service that is part of infrastructure-service-group that is set on NuvlaEdge, I suggest immediately setting the execution mode of the logs fetching job to `pull` if the NuvlaEdge has `NUVLA_JOB_PULL` capability.

**Comment by schaubl** [comment]
@konstan This has been done in:
- #822 
   (for adding support for `pull` mode deployment logs on NE)
- #808 
   (for setting deployment [and so deployment logs jobs] to `pull` mode when supported by NE)
