### ISSUE TITLE
COE specific attributes for infra_service

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#98]
the infrastructure_service_swarm and _kubernetes need the following additional attributes:

```
"nodes": [
  {
    "machine-name": "somestring",
    "machine-config-base64": "fuhwr2f=="
  }
],
"multiplicity": 1
```

# Current status

`nodes` is part of the `infrastructure_service` schema, but should be COE specific.

There's WIP here, but not finalized nor working properly: https://github.com/nuvla/api-server/tree/swarm-nodes

**Needs discussion**

**Comment by loomis** [comment]
The schema for these resources diverges too radically from the standard generic infrastructure service schema.  The resource should be refactored to allow for subtypes of the infrastructure service, each with their own schema.

**Comment by cjdcordeiro** [comment]
agreed

**Comment by cjdcordeiro** [comment]
@konstan is this still applicable or can it be closed?

**Comment by konstan** [comment]
@cjdcordeiro you can close this one. It is now infrastructure-service-coe with swarm and kubernetes subtypes. `nodes` attr is there in both of them. Entry in `nodes` for swarm and kubernetes differ by `kube-config` in the case of K8s nodes. This last one should go to a separate creds resource https://github.com/nuvla/api-server/issues/374.
